spring:
  web:
    resources:
      cache:
        cachecontrol:
          max-age: 31536000
          s-max-age: 31536000
          must-revalidate: true
          proxy-revalidate: true
          no-transform: true
  jackson:
    mapper:
      accept-case-insensitive-enums: true
    deserialization:
      read-unknown-enum-values-using-default-value: true
  jpa:
   generate-ddl: false
   hibernate:
    ddl-auto: validate
management:
  server:
    port: 8082
  endpoints:
    web:
      exposure:
        include: health,prometheus
server:
  compression:
    enabled: true
  http2:
    enabled: true
  servlet:
    encoding:
      charset: UTF-8
      force: true
    context-path: ${IDENTITY_BASE_PATH:}
  max-http-request-header-size: ${SERVER_REQUEST_HEADER_MAX_SIZE:8KB}
