camunda:
  client:
    mode: saas
    tenant-ids:
      - <default>
    auth:
      issuer: https://login.cloud.camunda.io/oauth/token
    zeebe:
      enabled: true
      audience: zeebe.camunda.io
      base-url: https://${camunda.client.region}.zeebe.camunda.io/${camunda.client.cluster-id}
      grpc-address: https://${camunda.client.cluster-id}.${camunda.client.region}.zeebe.camunda.io
      prefer-rest-over-grpc: false
    identity:
      enabled: false


