services:
  postgres:
    container_name: postgres
    image: postgres:16.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: identity
      POSTGRES_USER: identity
      POSTGRES_PASSWORD: "t2L@!AqSMg8%I%NmHM"
    networks:
      - identity-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.4
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
      - path.repo=/usr/local/els-snapshots
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
      - 9300:9300
    restart: always
    networks:
      - identity-network
    volumes:
      - ./els-snapshots:/usr/local/els-snapshots

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.4
    ports:
      - 5601:5601
    environment:
      - elasticsearch.hosts=elasticsearch:9200
    depends_on:
      - elasticsearch
    networks:
      - identity-network

  keycloak:
    depends_on:
      - postgres
    container_name: keycloak
    image: bitnami/keycloak:24.0.4
    ports:
      - "18080:8080"
    environment:
      KEYCLOAK_HTTP_RELATIVE_PATH: /auth
      KEYCLOAK_DATABASE_HOST: postgres
      KEYCLOAK_DATABASE_NAME: identity
      KEYCLOAK_DATABASE_USER: identity
      KEYCLOAK_DATABASE_PASSWORD: "t2L@!AqSMg8%I%NmHM"
      KEYCLOAK_ADMIN_USER: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/auth"]
      interval: 30s
      timeout: 15s
      retries: 8
      start_period: 30s
    networks:
      - identity-network

  identity:
    depends_on:
      keycloak:
        condition: service_healthy
    restart: on-failure
    container_name: identity
    image: camunda/identity:8.5.2
    ports:
      - "8084:8084"
    environment:
      SERVER_PORT: 8084
      KEYCLOAK_URL: http://keycloak:8080/auth
      IDENTITY_AUTH_PROVIDER_BACKEND_URL: http://keycloak:8080/auth/realms/camunda-platform
      IDENTITY_DATABASE_HOST: postgres
      IDENTITY_DATABASE_PORT: 5432
      IDENTITY_DATABASE_NAME: identity
      IDENTITY_DATABASE_USERNAME: identity
      IDENTITY_DATABASE_PASSWORD: "t2L@!AqSMg8%I%NmHM"
      KEYCLOAK_INIT_OPERATE_SECRET: the-cake-is-alive
      KEYCLOAK_INIT_OPERATE_ROOT_URL: http://localhost:8081
      KEYCLOAK_INIT_TASKLIST_SECRET: the-cake-is-alive
      KEYCLOAK_INIT_TASKLIST_ROOT_URL: http://localhost:8082
      IDENTITY_LOG_LEVEL: DEBUG
      MULTITENANCY_ENABLED: true
      KEYCLOAK_INIT_ZEEBE_NAME: Zeebe
      KEYCLOAK_INIT_ZEEBE_SECRET: zecret
      KEYCLOAK_CLIENTS_0_NAME: Zeebe
      KEYCLOAK_CLIENTS_0_ID: zeebe
      KEYCLOAK_CLIENTS_0_SECRET: zecret
      KEYCLOAK_CLIENTS_0_TYPE: M2M
      KEYCLOAK_CLIENTS_0_PERMISSIONS_0_RESOURCE_SERVER_ID: zeebe-api
      KEYCLOAK_CLIENTS_0_PERMISSIONS_0_DEFINITION: write:*
    env_file: .env.test
    networks:
      - identity-network

  zeebe:
    depends_on:
      - elasticsearch
    container_name: zeebe
    image: camunda/zeebe:8.5.1
    environment:
      - "JAVA_TOOL_OPTIONS=-Xms512m -Xmx512m"
      - ZEEBE_HOST=${ZEEBE_HOST:-}
      - ZEEBE_BROKER_CLUSTER_PARTITIONS_COUNT=4
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_INDEX_DEPLOYMENT=false
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_CLASSNAME=io.camunda.zeebe.exporter.ElasticsearchExporter
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_URL=http://elasticsearch:9200
      - ZEEBE_BROKER_EXPORTERS_ELASTICSEARCH_ARGS_BULK_SIZE=1
      - ZEEBE_BROKER_GATEWAY_MULTITENANCY_ENABLED=true
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_MODE=identity
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_TYPE=keycloak
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_ISSUERBACKENDURL=http://keycloak:8080/auth/realms/camunda-platform
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_AUDIENCE=zeebe-api
      - ZEEBE_BROKER_GATEWAY_SECURITY_AUTHENTICATION_IDENTITY_BASEURL=http://identity:8084
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
    ports:
      - 26500:26500
      - 8000:8000
      - 8089:8080
    restart: always
    networks:
      - identity-network

  operate:
    depends_on:
      identity:
        condition: service_started
      zeebe:
        condition: service_started
      elasticsearch:
        condition: service_started
    image: camunda/operate:8.5.2
    container_name: operate
    environment:
      - SERVER_PORT=8081
      - CAMUNDA_OPERATE_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_OPERATE_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_OPERATE_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=dev-data,identity-auth
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_URL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_ISSUER_BACKEND_URL=http://keycloak:8080/auth/realms/camunda-platform
      - CAMUNDA_OPERATE_IDENTITY_CLIENT_ID=operate
      - CAMUNDA_OPERATE_IDENTITY_CLIENT_SECRET=the-cake-is-alive
      - CAMUNDA_OPERATE_IDENTITY_AUDIENCE=operate-api
      - CAMUNDA_OPERATE_BACKUP_REPOSITORYNAME=test
      - CAMUNDA_OPERATE_MULTITENANCY_ENABLED=true
      - ZEEBE_CLIENT_ID=zeebe
      - ZEEBE_CLIENT_SECRET=zecret
      - ZEEBE_AUTHORIZATION_SERVER_URL=http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/token
      - ZEEBE_TOKEN_AUDIENCE=zeebe-api
    ports:
      - 8081:8081
    networks:
      - identity-network

  tasklist:
    depends_on:
      identity:
        condition: service_started
      zeebe:
        condition: service_started
      elasticsearch:
        condition: service_started
    restart: on-failure
    image: camunda/tasklist:8.5.1
    container_name: tasklist
    environment:
      - SERVER_PORT=8082
      - CAMUNDA_TASKLIST_ZEEBE_GATEWAYADDRESS=zeebe:26500
      - CAMUNDA_TASKLIST_ZEEBE_RESTADDRESS=http://zeebe:8080
      - CAMUNDA_TASKLIST_ELASTICSEARCH_URL=http://elasticsearch:9200
      - CAMUNDA_TASKLIST_ZEEBEELASTICSEARCH_URL=http://elasticsearch:9200
      - SPRING_PROFILES_ACTIVE=identity-auth,dev,dev-data
      - CAMUNDA_TASKLIST_IDENTITY_ISSUERURL=http://localhost:18080/auth/realms/camunda-platform
      - CAMUNDA_TASKLIST_IDENTITY_ISSUERBACKENDURL=http://keycloak:8080/auth/realms/camunda-platform
      - CAMUNDA_TASKLIST_IDENTITY_BASEURL=http://identity:8084
      - CAMUNDA_TASKLIST_IDENTITY_CLIENT_ID=tasklist
      - CAMUNDA_TASKLIST_IDENTITY_CLIENT_SECRET=the-cake-is-alive
      - CAMUNDA_TASKLIST_IDENTITY_AUDIENCE=tasklist-api
      - CAMUNDA_TASKLIST_IDENTITY_RESOURCE_PERMISSIONS_ENABLED=true
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUERURI=http://keycloak:8080/auth/realms/camunda-platform
      - SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWKSETURI=http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/certs
      - CAMUNDA_TASKLIST_BACKUP_REPOSITORYNAME=test
      - CAMUNDA_TASKLIST_MULTITENANCY_ENABLED=true
      - ZEEBE_CLIENT_ID=zeebe
      - ZEEBE_CLIENT_SECRET=zecret
      - ZEEBE_AUTHORIZATION_SERVER_URL=http://keycloak:8080/auth/realms/camunda-platform/protocol/openid-connect/token
      - ZEEBE_TOKEN_AUDIENCE=zeebe-api
    ports:
      - 8082:8082
    networks:
      - identity-network

networks:
  identity-network: {}
