# This workflow sends daily statistics about open renovate PRs.
# The statistics includes the reference to the PR, when it was opened and the current status.
name: Daily Renovate status

on:
  workflow_dispatch: { }
  schedule:
    # Runs at 10:00 every week day; see this link for more: https://crontab.guru/#0_1_*_*_1-5
    - cron: '0 10 * * 1-5'

jobs:
  extract-renovate-pr-status:
    name: Extract renovate PR status details
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    permissions:
      checks: read
      pull-requests: write
    outputs:
      status: ${{ steps.check-prs.outputs.status }}
    steps:
      - uses: actions/checkout@v4
      - id: check-prs
        name: Check for renovate PRs
        run: |
          renovatePrs=$(gh pr list --author 'app/renovate' --json=title,number,createdAt,mergeStateStatus)
          readarray -t prs < <( echo $renovatePrs | jq -c '.[]')
          renovateStatusString=""
          for pr in "${prs[@]}"
          do
            # extracting the data to create a nice message
            title=$(echo $pr | jq --raw-output '.title')
            prNumber=$(echo $pr | jq --raw-output '.number')
            createdAt=$(echo $pr | jq --raw-output '.createdAt')
            status=$(echo $pr | jq --raw-output '.mergeStateStatus')

            renovateStatusString+="\n • <https://github.com/camunda/camunda/pull/$prNumber|PR $prNumber ($status)>: $title (created $createdAt)"
          done

          echo "status=${renovateStatusString}" >> $GITHUB_OUTPUT
  slack-notify:
    name: Send slack notification for Renovate PR status
    runs-on: ubuntu-latest
    needs: extract-renovate-pr-status
    steps:
      - id: slack-notify
        name: Send slack notification to DevEx
        uses: slackapi/slack-github-action@v1.26.0
        with:
          # For posting a rich message using Block Kit
          payload: |
            {
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": ":renovate-party: *Daily Renovate status:* :renovate-party:"
                  }
                },
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "${{ needs.extract-renovate-pr-status.outputs.status }}"
                  }
                }
              ]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK
