# This GitHub Actions workflow that is triggered on push to `main` and `stable/**` branch or on any pull request creation
# and invokes `ci-build-reusable` and `ci-test-reusable` workflows.
---
name: Operate CI
on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
      - 'stable/**'
      - 'release/**'
    paths:
      - '.ci/**'
      - '.github/actions/**'
      - '.github/workflows/operate-*'
      - 'bom/*'
      - 'operate.Dockerfile'
      - 'operate/**'
      - 'parent/*'
      - 'pom.xml'
  pull_request:
    paths:
      - '.ci/**'
      - '.github/actions/**'
      - '.github/workflows/operate-*'
      - 'bom/*'
      - 'operate/**'
      - 'pom.xml'
      - 'operate.Dockerfile'
      - 'parent/*'

# This will limit the workflow to 1 concurrent run per ref (branch / PR).
# If a new commits occurs, the current run will be canceled to save costs.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  run-build:
    name: Operate Build
    uses: ./.github/workflows/operate-ci-build-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }} # head_ref = branch name on PR, ref_name = `main` or `stable/**`

  java-checks:
    name: Operate Java Checks
    uses: ./.github/workflows/operate-ci-build-observe-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      command: mvn -f operate verify -T1C -B -P spotbugs,skipFrontendBuild -DskipTests -DskipDockerProfile -DskipQaBuild
      runner-type: gcp-core-4-default

  run-unit-tests:
    name: Operate Backend Unit Tests
    uses: ./.github/workflows/operate-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      command: mvn -f operate verify -T1C -B -P skipFrontendBuild -DskipITs -DskipDockerProfile -DskipChecks
      test-type: Unit Tests
      runner-type: gcp-core-4-default

  run-integration-tests:
    name: Operate Backend Integration Tests
    uses: ./.github/workflows/operate-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      command: mvn -f operate/qa/integration-tests verify -P operateItStage1 -B -DskipChecks -Dfailsafe.rerunFailingTestsCount=2
      test-type: Integration Tests
      runner-type: gcp-core-32-default

  run-opensearch-tests:
    name: Operate Backend Opensearch ITs
    uses: ./.github/workflows/operate-ci-test-reusable.yml
    secrets: inherit
    with:
      branch: ${{ github.head_ref || github.ref_name }}
      command: mvn -f operate/qa/integration-tests verify -P operateItOpensearch,docker-opensearch -B -DskipChecks -Dfailsafe.rerunFailingTestsCount=2
      test-type: Opensearch ITs
      runner-type: gcp-core-32-default

  test-summary:
    # Used by the merge queue as a dummy instead of the Zeebe CI in case only Operate files got changed:
    # https://github.com/orgs/community/discussions/26251
    # This name is hard-coded in the branch rules; remember to update that if this name changes
    name: Test summary
    if: always()
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
